import esbuild from 'esbuild';
import process from 'process';
import builtins from 'builtin-modules';
import fs from 'fs';
import path from 'path';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

// Build JavaScript
const jsContext = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ['src/main.ts'],
  bundle: true,
  // Embed imported assets (e.g. wave.svg) as base64 data URLs directly in the bundle
  loader: {
    '.svg': 'dataurl',
  },
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    ...builtins,
  ],
  format: 'cjs',
  target: 'es2022',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outfile: 'main.js',
  minify: prod,
});

// Combine all CSS files into a single styles.css
function combineCssFiles() {
  const stylesDir = path.join(process.cwd(), 'src', 'styles');
  const outputFile = path.join(process.cwd(), 'styles.css');

  // Add header comment explaining this is a generated file
  let combinedCss = `/*
 * THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
 * This file is automatically generated by concatenating all CSS files from src/styles/
 * DO NOT EDIT THIS FILE DIRECTLY
 * To modify styles, edit the individual CSS files in src/styles/ directory
 */
`;

  let cssFiles = [];

  // Check if styles directory exists
  if (fs.existsSync(stylesDir)) {
    const files = fs.readdirSync(stylesDir);
    cssFiles = files.filter((file) => file.endsWith('.css'));

    cssFiles.forEach((file) => {
      const filePath = path.join(stylesDir, file);
      const content = fs.readFileSync(filePath, 'utf8');
      combinedCss += content + '\n\n';
    });
  }

  // Write the combined CSS file
  fs.writeFileSync(outputFile, combinedCss);
  console.log(`Combined ${cssFiles.length} CSS files into styles.css`);
}

if (prod) {
  await jsContext.rebuild();
  combineCssFiles();
  process.exit(0);
} else {
  await jsContext.watch();

  // Watch CSS files for changes during development
  const stylesDir = path.join(process.cwd(), 'src', 'styles');
  if (fs.existsSync(stylesDir)) {
    fs.watch(stylesDir, { recursive: true }, (eventType, filename) => {
      if (filename && filename.endsWith('.css')) {
        console.log('CSS file changed, rebuilding styles.css...');
        combineCssFiles();
      }
    });
    // Initial CSS build
    combineCssFiles();
  }
}
